### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by ahmedmaria** [DPigeon/SOEN341-Project#4]
isn't T-06 and T-07 same?
what about 02 and 03?

**Comment by RuslanSinyavsky** [comment]
T-2 and T-3 should work. As changing a password could be done when you know your current password and you just want to change it. And retrieving the password would be in a form of a request i suppose, as the user does not remember his/her password and must send a request to retrieve his/her credentials.(That`s how I see it).
As for T-6 and T-7, I see your point and i believe it is the same thing and we should remove one of them. 
If anyone has any other thought?
By the way, I am not sure I thought you could go directly to the issue from this page? I did not find a way to directly access the file from here so had to go to wiki.

**Comment by DPigeon** [comment]
T-02 and T-03 are not the same because T-02 will be useful for a teacher to change his password on his profile page. On the other side, retrieve means that you forgot your password and you want to retrieve it before logging in again.

For T-06 and T-07, I believe that they are the same. I mean, only the Admin will be able to delete a child from a class (meaning that he will be deleted forever in the database but that is not really needed on our project). So yes, I think we should keep the term 'remove' because a teacher can definitely remove a child from their class. I say let's keep T-06 and delete T-07.

**Comment by AnasBuyumad** [comment]
Yes T06 and T07 are duplicates (and my bad, didn't see how I didn't notice that when we did the meeting)

A teacher can only remove a child from its class and not delete a child, as it would mean deleting it from the system as DPigeon said, so let's keep T06 and remove T07.

For T02 and T03, Dpigeon's is clear about that, both are needed.
